package compiler.util;

public enum ERROR {
	LEXICAL_ERROR,
	SYNTAX_ERROR,
	VERSION_ERROR,
	ATTRIBUTE_ERROR,
	WINDOWOPTION_ERROR,
	IOPINATTR_ERROR,
	SYMBOLTYPE_ERROR,
	MIRRORTYPE_ERROR,
	ROTATIONTYPE_ERROR,
	ROTMIRR_ERROR,
	SYMATTRTYPE_ERROR,
	DESCRIPTION_ERROR,
	TYPE_ERROR,
	SPICELINEVALUE_ERROR,
	SYMBOLTYPENULL_ERROR,
	MISS_TYPEATTR_ERROR,
	MISS_DESCATTR_ERROR
}
