package com.omega.compiler.util.error;

public enum Error {
	LEXICAL_ERROR,
	SYNTAX_ERROR,
	VERSION_ERROR,
	ATTRIBUTE_ERROR,
	WINDOWOPTION_ERROR,
	IOPINATTR_ERROR,
	SYMBOLTYPE_ERROR,
	MIRRORTYPE_ERROR,
	ROTATIONTYPE_ERROR,
	ROTMIRR_ERROR,
	SYMATTRTYPE_ERROR,
	DESCRIPTION_ERROR,
	TYPE_ERROR,
	SPICELINEVALUE_ERROR,
	SYMBOLTYPENULL_ERROR,
	MISS_TYPEATTR_ERROR,
	MISS_DESCATTR_ERROR,
	SYMBOLTYPE_TO_IMPLEMENT,
	DESCRIPTION_POLARIZED_ERROR,
	DESCRIPTION_NOT_ALLOWED,
	DESCRIPTION_POLARIZED_NOCAPACITOR_ERROR
}
